[mypy]
python_version = 3.10
strict = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true

[mypy-kivy.*]
ignore_missing_imports = true

[mypy-kivymd.*]
ignore_missing_imports = true

[mypy-plyer.*]
ignore_missing_imports = true

[mypy-websockets.*]
ignore_missing_imports = true

[mypy-pytest.*]
ignore_missing_imports = true
